### ISSUE TITLE
Move this repo under another org?

### ISSUE THREAD

**Issue by martinRenou** [emscripten-forge/requests-wasm-polyfill#1]
I was wondering if we could move this repo under the `emscripten-forge` org?

And maybe taking the opportunity to rename it to `requests-wasm-polyfill` as suggested by @wolfv?

**Comment by martinRenou** [comment]
Thank you for moving it @DerThorsten ! Would you be able to also rename it to `requests-wasm-polyfill`?

**Comment by DerThorsten** [comment]
sure

**Comment by westurner** [comment]
- https://github.com/koenvo/pyodide-http/issues/6
