### ISSUE TITLE
Patch `urllib.urlopen`

### ISSUE THREAD

**Issue by jtpio** [emscripten-forge/requests-wasm-polyfill#4]
It would be nice to also patch `urllib.urlopen` by default as it is also commonly used.

For example `pyodide-http` supports it: https://github.com/koenvo/pyodide-http#supported-packages

![image](https://user-images.githubusercontent.com/591645/231967992-5818f965-cfb3-4656-b284-b3696f667929.png)

**Comment by jtpio** [comment]
Or maybe this could be a separate repo / package under `emscripten-forge/requests-urllib-polyfill`?

**Comment by DerThorsten** [comment]
Best would be to make https://github.com/koenvo/pyodide-http usable with pyjs remove this repo

**Comment by jtpio** [comment]
Sounds good.

**Comment by jonas-w** [comment]
@DerThorsten is there something that blocks porting pyodide-http to emscripten? Currently, just used pyodide and wanted to try out the jupyterlite-xeus kernel, but the requests package on emscripten breaks many things for me, compared to pyodide where most stuff worked after some tweaks.

**Comment by jtpio** [comment]
Closing as this is not needed anymore: https://github.com/emscripten-forge/recipes/issues/782
